### ISSUE TITLE
[display real data] connect to github api

### ISSUE THREAD

**Issue by giogonzo** [nerder/gh-explorer#22]
## requirements
- fetch real results from github
## sub issues
- [x] fetch real results #21
- [x] show a loader while fetching results #23 
- [x] Handle API errors and show them out #31
